version: '3.5'

volumes:
  data:

services:
  pg_database:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./pyspark_data:/projetos/data

    command: tail -f /dev/null

